// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace DentalClaims.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("DentalClaims.Domain.Models.ConsultaOdontologica", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("CRODentista")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("DataConsulta")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(10)");

                b.Property<string>("Dentista")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("HorarioConsulta")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(48)");

                b.Property<string>("Observacoes")
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("Status")
                    .HasColumnType("NUMBER(10)");

                b.Property<int>("UsuarioId")
                    .HasColumnType("NUMBER(10)");

                b.HasKey("Id");

                b.HasIndex("UsuarioId");

                b.ToTable("Consultas");
            });

            modelBuilder.Entity("DentalClaims.Domain.Models.Tratamento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<int>("ConsultaId")
                    .HasColumnType("NUMBER(10)");

                b.Property<decimal>("Custo")
                    .HasColumnType("DECIMAL(18, 2)");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("Id");

                b.HasIndex("ConsultaId");

                b.ToTable("Tratamento");
            });

            modelBuilder.Entity("DentalClaims.Domain.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("CPF")
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("DataNascimento")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(10)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("DentalClaims.Domain.Models.ConsultaOdontologica", b =>
            {
                b.HasOne("DentalClaims.Domain.Models.Usuario", "Usuario")
                    .WithMany("Consultas")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("DentalClaims.Domain.Models.Tratamento", b =>
            {
                b.HasOne("DentalClaims.Domain.Models.ConsultaOdontologica", "Consulta")
                    .WithMany("Tratamentos")
                    .HasForeignKey("ConsultaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Consulta");
            });

            modelBuilder.Entity("DentalClaims.Domain.Models.ConsultaOdontologica", b =>
            {
                b.Navigation("Tratamentos");
            });

            modelBuilder.Entity("DentalClaims.Domain.Models.Usuario", b =>
            {
                b.Navigation("Consultas");
            });
#pragma warning restore 612, 618
        }
    }
}
